repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args:
          # compatibility with black
          - "--max-line-length=88"
          # E741 ambiguous variable name 'I'
          # W503 line break before binary operator
          - "--ignore=E741,W503"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'
    hooks:
       - id: mypy
         additional_dependencies: [types-PyYAML==6.0.12.20250516]
